"use client"; // This must be at the top for useState and onClick to work

import React, { useState } from "react";
import axios from "axios";
import { Loader2, AlertTriangle, Zap } from "lucide-react";

// --- Use standard alias paths defined in tsconfig.json ---
import { SearchForm, SearchFormState } from "@/components/SearchForm";
import { StockChart } from "@/components/StockChart";
import { InvestmentAdvice } from "@/components/InvestmentAdvice";
import { RecommendedStocks } from "@/components/RecommendedStocks";
import { AnalysisSummary } from "@/components/AnalysisSummary"; 

// Get the API URL from the environment file
// Next.js requires the prefix NEXT_PUBLIC_ to access it in the browser
const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000";

// --- Define the structure of the API response ---
// This matches the JSON output from our Python backend
export interface ForecastData {
  month: string;
  price: number;
  type: 'history' | 'forecast';
}

export interface InvestmentAdviceData {
  entryPoint: number;
  expectedReturn: number;
  stopLoss: number;
}

export interface RecommendedStockData {
  ticker: string;
  name?: string; // Make optional to match your team's component
  reason: string;
}

export interface AnalysisResult {
  analysis: string;
  keyNews: string;
  forecastData: ForecastData[];
  investmentAdvice: InvestmentAdviceData;
  recommendedStocks: RecommendedStockData[];
}

// --- The Main Page Component ---
export default function Home() {
  // --- 1. State Management ---
  
  // State for the form inputs
  const [formState, setFormState] = useState<SearchFormState>({
    ticker: "AAPL",
    financialCondition: ["Stable Income"],
    expectedReturn: 15,
    riskTolerance: "Medium",
    tradingPreferences: "I am a long-term holder, I prefer tech.",
  });

  // State for the API call
  const [isLoading, setIsLoading] = useState(false);
  const [apiError, setApiError] = useState<string | null>(null);

  // State for the final results
  const [results, setResults] = useState<AnalysisResult | null>(null);

  // --- 2. API Call Logic ---
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setApiError(null);
    setResults(null); // Clear old results

    try {
      // Call our Python FastAPI backend
      const response = await axios.post(
        `${API_BASE_URL}/api/analyze`,
        formState
      );

      if (response.data.error) {
        throw new Error(response.data.error);
      }

      const aiResponseJsonString = response.data.analysis;
      if (!aiResponseJsonString) {
        throw new Error("Empty response from AI");
      }

      // Parse the JSON string from the backend
      const aiData: AnalysisResult = JSON.parse(aiResponseJsonString);
      
      // Save the results to our state
      setResults(aiData);

    } catch (error: any) {
      console.error("Error fetching analysis:", error);
      let errorMessage = "Failed to fetch analysis.";
      if (error.response) {
        errorMessage = `Server Error: ${error.response.data.detail || error.message}`;
      } else if (error.request) {
        errorMessage = `Connection Error: Is the Python server running at ${API_BASE_URL}?`;
      } else {
        errorMessage = error.message;
      }
      setApiError(errorMessage);
    } finally {
      setIsLoading(false);
    }
  };

  // --- 3. Render the Page ---
  return (
    <main className="flex min-h-screen flex-col md:flex-row bg-gray-100 dark:bg-gray-950">
      {/* --- Left Column: The Form --- */}
      <aside className="w-full md:w-1/3 lg:w-1/4 p-6 bg-gray-50 dark:bg-gray-900 overflow-y-auto h-screen sticky top-0">
        <h2 className="text-3xl font-bold mb-6 text-indigo-600 dark:text-indigo-400">
          AI Stock Analyzer
        </h2>
        
        <SearchForm
          formState={formState}
          // This allows the child component to update the parent's state
          setFormState={(updater) => setFormState(updater(formState))}
          handleSubmit={handleSubmit}
          isLoading={isLoading}
        />
        <div className="mt-8 text-xs text-gray-500 dark:text-gray-400">
          <p className="font-bold">Disclaimer:</p>
          <p>
            This is not financial advice. All analysis is generated by an AI and is for informational purposes only.
          </p> 
          {/* --- FIX: Corrected closing </Click> tag to </p> --- */}
        </div>
      </aside>

      {/* --- Right Column: The Dashboard --- */}
      <section className="flex-1 p-10 overflow-y-auto h-screen">
        <h1 className="text-4xl font-bold mb-8 text-gray-900 dark:text-white">
          Analysis Dashboard
        </h1>

        {/* Handle Loading State */}
        {isLoading && (
          <div className="flex flex-col justify-center items-center h-96">
            <Loader2 className="animate-spin h-16 w-16 text-indigo-600" />
            <h3 className="mt-4 text-xl font-semibold text-gray-700 dark:text-gray-300">
              Analyzing...
            </h3>
            <p className="text-gray-500 dark:text-gray-400">
              Please wait, the AI is processing your request.
            </p>
          </div>
        )}

        {/* Handle Error State */}
        {apiError && !isLoading && (
          <div className="flex flex-col justify-center items-center h-96">
            <AlertTriangle className="h-16 w-16 text-red-500" />
            <h3 className="mt-4 text-xl font-semibold text-red-600">
              An Error Occurred
            </h3>
            <p className="text-gray-500 dark:text-gray-400 text-center max-w-md">
              {apiError}
            </p>
          </div>
        )}

        {/* Handle Success State: Show all the results */}
        {results && !isLoading && !apiError && (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* Left Column (Forecast & Advice) */}
            <div className="lg:col-span-2 space-y-8">
              <StockChart data={results.forecastData} />
              <InvestmentAdvice data={results.investmentAdvice} />
            </div>

            {/* Right Column (Recommendations & Summary) */}
            <div className="lg:col-span-1 space-y-8">
              <RecommendedStocks data={results.recommendedStocks} />
              <AnalysisSummary
                analysis={results.analysis}
                keyNews={results.keyNews}
              />
            </div>
          </div>
        )}

        {/* Initial Empty State */}
        {!results && !isLoading && !apiError && (
          <div className="flex flex-col justify-center items-center h-96 border-2 border-dashed border-gray-300 dark:border-gray-700 rounded-lg">
            <Zap className="h-16 w-16 text-gray-400" />
            <h3 className="mt-4 text-xl font-semibold text-gray-700 dark:text-gray-300">
              Run an Analysis
            </h3>
            <p className="text-gray-500 dark:text-gray-400">
              Fill out the form on the left and click "Analyze" to see your results.
            </p>
            {/* --- FIX: Corrected closing </WELCOME> tag to </p> --- */}
          </div>
        )}
      </section>
    </main>
  );
}
